# action.yml
name: 'Build Qemu Coreboot'
description: 'Build coreboot for x86_64 qemu emulation'
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install Tools
      shell: bash
      run: sudo apt-get install -y bison build-essential curl flex git gnat libncurses5-dev m4 zlib1g-dev

    - name: Build Toolchain
      shell: bash
      run: make crossgcc-i386 CPUS=$(nproc)

    - name: Build Payload
      shell: bash
      run: make payloads/external/SeaBIOS
      
    - name: Copy QEMU Config
      shell: bash
      run: cp configs/config.emulation_qemu_x86_i440fx ./.config

    - name: Set Default Options
      shell: bash
      run: make olddefconfig

    - name: Build Coreboot
      shell: bash
      run: make -j$(nproc)

    - uses: actions/upload-artifact@v3
      with:
        name: most-recent-build
        path: ./build/coreboot.rom
