---
name: Workflow
on:
  push:

jobs:
  CloneAssets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: firmwareci/coreboot-assets
          token: ${{ secrets.PAT }}
      - uses: jakejarvis/wait-action@master
        with:
          time: '10s'
      - uses: actions/upload-artifact@v3
        with:
          name: coreboot-assets
          path: ./3rdparty/blobs/mainboard/

  BuildQemuX86:
    runs-on: ubuntu-latest
    needs: CloneAssets
    steps:
      - uses: actions/checkout@v3
      - name: Build Action
        uses: ./.github/actions/buildQemuX86

  UploadBinaryForTesting: 
    needs: BuildQemuX86
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: coreboot-image
          path: ./coreboot.rom

      - uses: docker://firmwareci/uploader:v0.1
        with:
          PROJECT_UUID: b8818c1e-5be3-40f7-b8c5-5902d73ce273
          BINARY_PATH: ./coreboot.rom
          PROTOCOL: s3
          API: http://78.94.0.50:8080/request
          UPLOAD_PATH: ./coreboot.rom

          S3_ACCESS: ${{ secrets.S3_ACCESS_ID }}
          S3_SECRET: ${{ secrets.S3_ACCESS_KEY }}
          S3_REGION: eu-central-1
          S3_BUCKET: ${{ secrets.S3_BUCKET }}

