---
name: Workflow
on:
  push:

jobs:
  BuildQemuX86:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Action
        uses: ./.github/actions/buildQemuX86

  UploadBinaryForTesting: 
    needs: BuildQemuX86
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: most-recent-build
          path: ./coreboot.rom

      - uses: docker://firmwareci/uploader:v0.1
        with:
          PROJECT_UUID: 54c3cf96-28ed-4aba-b59c-6f8c954c4dda
          BINARY_PATH: ./coreboot.rom
          PROTOCOL: s3
          API: http://78.94.0.50:8080/request
          UPLOAD_PATH: ./coreboot.rom

          S3_ACCESS: ${{ secrets.S3_ACCESS_ID }}
          S3_SECRET: ${{ secrets.S3_ACCESS_KEY }}
          S3_REGION: eu-central-1
          S3_BUCKET: ${{ secrets.S3_BUCKET }}

